Web/src/MercuryHealth.Web/Controllers/FoodLogEntriesController.cs
#region Namespaces
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MercuryHealth.Models;
using MercuryHealth.Web.Models;
using System.Diagnostics;
using Microsoft.ApplicationInsights;
#endregion

namespace MercuryHealth.Web.Controllers
{

    public class FoodLogEntriesController : Controller
    {

        private IFoodLogEntryRepository repository;

        public FoodLogEntriesController(IFoodLogEntryRepository repo)
        {
            this.repository = repo;
        }

        public FoodLogEntriesController() : this(new FoodLogEntrySqlRepository())
        {

        }

        // GET: FoodLogEntries
        public ActionResult Index()
        {
            return View(repository.GetAll().ToList());
            // added a comment
        }

        // GET: FoodLogEntries/Details/5
        public ActionResult Details(int? id)
        {
            // added some code
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodLogEntry foodLogEntry = repository.Get(id);
            if (foodLogEntry == null)
            {
                return HttpNotFound();
            }
            return View(foodLogEntry);
        }

        // GET: FoodLogEntries/Create
        public ActionResult Create()
        {

            var query = new FoodLogEntry
            {
                Quantity = 1,
                Description = "Apple",
                //MealTime = DateTime.UtcNow,
                MealTime = Convert.ToDateTime("8/25/2105"),
                Calories = 116,
                Tags = "fruit, snack",
                ProteinInGrams = Convert.ToDecimal("0.6"),
                FatInGrams = Convert.ToDecimal("0.4"),
                CarbohydratesInGrams = Convert.ToDecimal("38.8"),
                SodiumInGrams = Convert.ToDecimal("2.0")
            };

            return View(query);
        }

        // POST: FoodLogEntries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FoodLogEntry foodLogEntry)
        //public ActionResult Create([Bind(Include = "Id,Quantity,Description,MealTime,Tags,Calories,ProteinInGrams,FatInGrams,CarbohydratesInGrams,SodiumInGrams,Color")] FoodLogEntry foodLogEntry)
        {
            if (ModelState.IsValid)
            {
                repository.Create(foodLogEntry);

                Trace.TraceInformation("Created FoodLogEntry {0}", foodLogEntry.Description);

                // Application Insights - Track Events
                var telemetry = new TelemetryClient();
                telemetry.TrackTrace("Created FoodLogEntry " + foodLogEntry.Id.ToString() + " " + foodLogEntry.Description);
                telemetry.TrackEvent("Created FoodLogEntry " + foodLogEntry.Id.ToString() + " " + foodLogEntry.Description);
                //if (!string.IsNullOrEmpty(foodLogEntry.Color))
                //{
                //    telemetry.TrackEvent("Creating new food with color field " + foodLogEntry.Id.ToString() + " Color: " + foodLogEntry.Color + " Description:" + foodLogEntry.Description);
                //}
 
                return RedirectToAction("Index");
            }

            return View(foodLogEntry);
        }

        // GET: FoodLogEntries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodLogEntry foodLogEntry = repository.Get(id);
            if (foodLogEntry == null)
            {
                return HttpNotFound();
            }
            return View(foodLogEntry);
        }

        // POST: FoodLogEntries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FoodLogEntry foodLogEntry)
        //public ActionResult Edit([Bind(Include = "Id,Quantity,Description,MealTime,Tags,Calories,ProteinInGrams,FatInGrams,CarbohydratesInGrams,SodiumInGrams,Color")] FoodLogEntry foodLogEntry)
        {
            if (ModelState.IsValid)
            {
                repository.Update(foodLogEntry);
                //if (!string.IsNullOrEmpty(foodLogEntry.Color))
                //{
                //    var telemetry = new TelemetryClient();
                //    telemetry.TrackEvent("Modified food with color field " + foodLogEntry.Id.ToString() + " Color: " + foodLogEntry.Color + " Description:" + foodLogEntry.Description);
                //}

                return RedirectToAction("Index");
            }
            return View(foodLogEntry);
        }

        // GET: FoodLogEntries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodLogEntry foodLogEntry = repository.Get(id);
            if (foodLogEntry == null)
            {
                return HttpNotFound();
            }
            return View(foodLogEntry);
        }

        // POST: FoodLogEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);

            return RedirectToAction("Index");
        }

        public ActionResult AddFoodFromTwitter(string food, string user)
        {
            var newFoodLogEntry = new FoodLogEntry
            {
                Description = food + " - from Twitter by " + user,
                Calories = 100,
                CarbohydratesInGrams = 99,
                FatInGrams = 12,
                MealTime = DateTime.Now,
                ProteinInGrams = 3,
                Quantity = 1,
                Tags = "From Twitter"

            };

            repository.Create(newFoodLogEntry);
            // Application Insights - Track Events
            var telemetry = new TelemetryClient();
            telemetry.TrackTrace("Created FoodLogEntry from twitter by " + user + ": " + newFoodLogEntry.Id.ToString() + " " + newFoodLogEntry.Description);
            telemetry.TrackEvent("Created FoodLogEntry from twitter by " + user + ": " + newFoodLogEntry.Id.ToString() + " " + newFoodLogEntry.Description);


            return null;
        }

    }

}

Web/src/MercuryHealth.Web/Controllers/MyMetricsController.cs
#region Namespaces
using MercuryHealth.Models;
using MercuryHealth.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
#endregion

namespace MercuryHealth.Web.Controllers
{

    public class MyMetricsController : Controller
    {

        ApplicationDbContext db = new ApplicationDbContext();

        // GET: MyMetrics
        public ActionResult Calculate()
        {
            var myMetricsVm = new MyMetricsViewModel();
            // Comment
            var currentUserId = User.Identity;
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            myMetricsVm.MemberProfile = db.Users
                .Include("MemberProfile")
                .Where(u => u.Id == currentUser.Id)
                .First()
                .MemberProfile;

            return View(myMetricsVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Calculate(MyMetricsViewModel myMetricsVm)
        {
            return View(myMetricsVm);
        }

    }

}

Web/src/MercuryHealth.Web/Views/Shared/_Layout.cshtml
@using MecuryHealth

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mercury Health</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    
    @*    Application Insights code to monitor web pages*@
    <script type="text/javascript">  var appInsights=window.appInsights||function(config){    function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t    }({        instrumentationKey:"b894173d-32e6-4862-9b55-76969fb21793"    });           window.appInsights=appInsights;    appInsights.trackPageView();</script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mercury Health Group", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Exercises", "Index", "Exercises")</li>
                    <li>@Html.ActionLink("Nutrition", "Index", "FoodLogEntries")</li>
                    <li>@Html.ActionLink("My Metrics", "Calculate", "MyMetrics")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.UtcNow.Year | Mercurty Health Group | @Helper.GetAssemblyVersionAndDate()</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>